import streamlit as st
# Configurações da página
st.set_page_config(page_title="Dicas", page_icon="📤")
st.markdown("# 🎓 10 Dicas para arrasar no seu TCC")
st.markdown("As dúvidas em como começar a escrever o TCC são várias, no entanto, toda a complicação e estresse desse trabalho podem ser evitados se a sua organização estiver em dia")
st.markdown("Listamos 10 dicas para te ajudar a arrasar no TCC")
st.markdown("1. Escolha um tema relevante e interessante: escolher um tema que seja relevante para a área de estudo e que seja de interesse pessoal facilita a realização da pesquisa e escrita do TCC.")
st.markdown("---")
st.markdown("2. Faça um planejamento: antes de começar a escrever, faça um planejamento que inclua a definição dos objetivos, a estrutura do trabalho e os prazos para cada etapa.")
st.markdown("---")
st.markdown("3. Pesquise bastante: busque informações em livros, artigos, periódicos, teses e dissertações que abordem o tema escolhido. É importante utilizar fontes confiáveis e atualizadas.")
st.markdown("---")
st.markdown("4. Organize suas ideias: após a pesquisa, organize as informações coletadas em tópicos e sub-tópicos, para facilitar a escrita do TCC.")
st.markdown("---")
st.markdown("5. Utilize a norma ABNT: siga as normas da ABNT para a estruturação do trabalho, citações e referências bibliográficas. Isso ajuda a dar credibilidade e padronizar o trabalho.")
st.markdown("---")
st.markdown("6. Escreva com clareza: seja claro e objetivo na escrita, evitando termos técnicos e jargões desnecessários. Utilize uma linguagem formal e coerente.")
st.markdown("---")
st.markdown("7. Releia e revise: após finalizar a escrita, revise o trabalho com atenção para evitar erros de gramática e ortografia. Peça a ajuda de um colega ou professor para revisar o trabalho.")
st.markdown("---")
st.markdown("8. Apresente o trabalho com confiança: prepare-se para defender o seu TCC com confiança e segurança. Treine a apresentação e esteja preparado para responder perguntas.")
st.markdown("---")
st.markdown("9. Seja ético: evite plágio e cite todas as fontes utilizadas no trabalho. Respeite os direitos autorais e siga as normas de ética acadêmica.")
st.markdown("---")
st.markdown("10. Tenha dedicação e comprometimento: o TCC demanda tempo e dedicação. Mantenha o foco e o comprometimento para entregar um trabalho de qualidade e que atenda aos objetivos propostos.")
st.markdown("---")